### ISSUE TITLE
jsPDF Autotable Error

### ISSUE THREAD

**Issue by omkargudekar** [sphilee/jsPDF-CustomFonts-support#14]
Error when used with Autotable.

Only added autotable and tried to export

```
    <script>
        var doc = new jsPDF();

        doc.addFont('HMKMMAG.TTF', 'MagicR', 'normal', 'Identity-H');
        doc.addFont('HMKMRHD.TTF', 'HeadlineR', 'normal', 'Identity-H');
        doc.addFont('msgothic.ttf', 'MsGothic', 'normal', 'Identity-H');
        doc.addFont('gothic.ttf', 'LiLing', 'normal', 'Identity-H');
        //doc.addFont('HARLOWSI.TTF', 'WMLWQI+HarlowSolid', 'normal', 'WinAnsiEncoding');
        //doc.addFont('ITCBLKAD.TTF','a','normal','WinAnsiEncoding');
        //doc.addFont('BOD_PSTC.TTF','b','normal','WinAnsiEncoding');
        //doc.addFont('GADUGI.TTF', 'GADUGI', 'normal', 'WinAnsiEncoding');



        doc.setFont('MagicR');        // set font
        doc.setFontSize(20);
        doc.setTextColor(153,051,102);
        doc.setCharSpace(3);

        //doc.setDefaultFonts(0, 'Times');    //English default
        //doc.setDefaultFonts(1, 'MagicR');    //Korean default
        doc.setDefaultFonts(3, 'LiLing');         //Chinese default
        doc.setDefaultFonts(2, 'MsGothic');        //Japanese default



		var columns = ["ID", "Name", "Country"];
		var rows = [
    		[1, "Shaw", "홍A平길Bお동安C"],
    		[2, "Nelson", "Kazakhstan"],
    		[3, "Garcia", "Madagascar"],
		];

		doc.autoTable(columns, rows,{styles: {font: "MsGothic"}});
		doc.save('table.pdf');
    </script>
```

got below error

Uncaught TypeError: Cannot read property 'widths' of undefined
    at Object.API.getCharWidthsArray (split_text_to_size.js:47:89)
    at Object.API.getStringUnitWidth (split_text_to_size.js:95:40)
jspdf.plugin.autotable.js:311:57
    at Array.forEach (native)
    at Object.getStringWidth (jspdf.plugin.autotable.js:310:10)
spdf.plugin.autotable.js:964:71
    at Array.forEach (native)
jspdf.plugin.autotable.js:962:44
    at Array.forEach (native)
    at Object.calculateWidths (jspdf.plugin.autotable.js:960:19)

**Comment by simonbengtsson** [comment]
Have you tried without setting custom fonts?

**Comment by TianDaGe** [comment]
same here.
I tested without setting custom fonts. same error was occurred.
Autotable function was working fine without customfont.js.

**Comment by TianDaGe** [comment]
@simonbengtsson , @sphilee  Is there any way to resolve this issue?
Your both works are very good. but I can't use your both :(

**Comment by TianDaGe** [comment]
Is there any update or news yet?

**Comment by ChengYuHin99** [comment]
@simonbengtsson  
Same issue here too.
Please help  to fix this issue. 
Thanks.

**Comment by alkincakiralar1996** [comment]
any solution?

**Comment by menty44** [comment]
TypeError: Cannot read property 'API' of undefined
